# Sharpmake AppVeyor CI configuration

image: Visual Studio 2017

platform:
- Any CPU

configuration:
- Debug
- Release

before_build:
- cmd: bootstrap.bat

for:
  -
    matrix:
      only:
        - configuration: Debug
    build_script:
      - CompileSharpmake.bat Sharpmake.sln Debug "Any CPU"

  -
    matrix:
      only:
        - configuration: Release
    build_script:
      - CompileSharpmake.bat Sharpmake.sln Release "Any CPU"

after_test:
- cmd: python regression_test.py

